version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    volumes:
      - /usr/src/app/packages/frontend/node_modules
      - ./packages/frontend:/usr/src/app/packages/frontend
      - /usr/src/app/packages/backend/node_modules
      - ./packages/backend:/usr/src/app/packages/backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.frontend.entryPoints=https

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    volumes:
      - /usr/src/app/packages/backend/node_modules
      - ./packages/backend:/usr/src/app/packages/backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`${DOMAIN}`)&&PathPrefix(`/api`)
      - traefik.http.routers.backend.entryPoints=https

  redis-cache:
    image: redis:6.0.6

  redis-ui:
    image: patrikx3/p3x-redis-ui:2020.10.315
    ports:
      - ${REDIS_UI_PORT}:7843
    volumes:
      - ./redis-ui/settings:/settings

  magento2:
    build: magento2
    image: magento2:latest
    volumes:
      - ${MAGENTO_DATA_FOLDER}:/var/www/html
    labels:
      - traefik.enable=true
      - traefik.http.routers.magento.rule=Host(`magento.${DOMAIN}`)
      - traefik.http.routers.magento.entryPoints=https
      - traefik.http.services.magento.loadbalancer.server.port=80

  magento2-phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    environment:
      - PMA_HOST=magento2-db
      - PMA_USER=${MAGENTO_MYSQL_USERNAME}
      - PMA_PASSWORD=${MAGENTO_MYSQL_PASSWORD}
    ports:
      - ${MAGENTO_PHPMYADMIN_PORT}:80

  traefik:
    image: traefik:v2.3
    ports:
      - ${TRAEFIK_HTTP_PORT}:80
      - ${TRAEFIK_HTTPS_PORT}:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_LETSENCRYPT_FOLDER}:/letsencrypt
      - ${TRAEFIK_LOG_PATH}:/var/log/traefik.log
      - ${TRAEFIK_ACCESS_LOG_PATH}:/var/log/access.log
    command:
      - --api.insecure=false
      - --api.dashboard=true
      - --log.level=INFO
      - --log.filepath=/var/log/traefik.log
      - --log.format=json
      - --accesslog=true
      - --accesslog.filepath=/var/log/access.log
      - --accesslog.bufferingsize=100
      - --accesslog.format=json
      - --accesslog.fields.defaultmode=keep
      - --accesslog.fields.headers.defaultmode=keep
      - --accesslog.fields.headers.names.Authorization=drop
      - --providers.docker=true
      - --providers.docker.swarmMode=false
      - --providers.docker.exposedByDefault=false
      - --entrypoints.https.address=:${TRAEFIK_HTTP_PORT}
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.entryPoints=https
