version: '3'
services:
  # frontend:
  #   build: frontend
  #   ports:
  #     - ${FRONTEND_PORT}:3000
  #   volumes:

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    ports:
      - ${BACKEND_PORT}:3000
    volumes:
      - /usr/src/app/packages/backend/node_modules
      - ./packages/backend:/usr/src/app/packages/backend

  magento2:
    build: magento2
    image: magento2:latest
    ports:
      - ${MAGENTO_PORT}:80
    volumes:
      - ${MAGENTO_DATA_FOLDER}:/var/www/html

  magento2-phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    environment:
      - PMA_HOST=magento2-db
      - PMA_USER=${MAGENTO_MYSQL_USERNAME}
      - PMA_PASSWORD=${MAGENTO_MYSQL_PASSWORD}
    ports:
      - ${MAGENTO_PHPMYADMIN_PORT}:80
