version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - /usr/src/app/packages/frontend/node_modules
      - ./packages/frontend:/usr/src/app/packages/frontend
      - /usr/src/app/packages/backend/node_modules
      - ./packages/backend:/usr/src/app/packages/backend

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    ports:
      - ${BACKEND_PORT}:3000
    volumes:
      - /usr/src/app/packages/backend/node_modules
      - ./packages/backend:/usr/src/app/packages/backend

  redis-cache:
    image: redis:6.0.6

  redis-ui:
    image: patrikx3/p3x-redis-ui:2020.10.315
    ports:
      - ${REDIS_UI_PORT}:7843
    volumes:
      - ./redis-ui/settings:/settings
  magento2:
    build: magento2
    image: magento2:latest
    ports:
      - ${MAGENTO_PORT}:80
    volumes:
      - ${MAGENTO_DATA_FOLDER}:/var/www/html

  magento2-phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    environment:
      - PMA_HOST=magento2-db
      - PMA_USER=${MAGENTO_MYSQL_USERNAME}
      - PMA_PASSWORD=${MAGENTO_MYSQL_PASSWORD}
    ports:
      - ${MAGENTO_PHPMYADMIN_PORT}:80
